# Personal Information
me:
  name: Long Gong
  web: "https://lgong30.github.io"
  address: 266 Ferst Dr, Atlanta, GA 30332, United States
  cellphone: +1(404)697-0608
  email: gonglong@gatech.edu

# Objective
objective:
  description: >-
    Internship position in the field of networking (with special interest in software defined networking and data center networking), scheduling in switches, and software engineering.
  term: Summer and Fall 2018

# Education Background
education:
  - institution:
      name: Georgia Institute of Technology
      address: Atlanta, GA, USA
    details:
      - degree: Ph.D. Candidate
        major: Computer Science
        performance: "GPA: 3.91/4.0"
        duration: 2015.8 - 2019.5 (\textbf{Expected})
  - institution:
      name: University of Science and Technology of China
      address: Hefei, Anhui, China
    details:
      - degree: M.Eng.
        major: Communication and Information Systems
        performance: "GPA: 3.81/4.3"
        duration: 2012.9 - 2015.6
      - degree: B.Eng.
        major: Electronic Information Engineering
        performance: "GPA: 3.75/4.3"
        duration: 2008.9 - 2012.6

# Intern Experience
experience:
  - institution: 
      name: "Alibaba Group (U.S.) Inc"
      address: Bellevue, WA, USA
    duration: 2018.5 - 2018.8
    role: Intern
    mentor: Gang Cheng
    achievements:
      - "Built a highly scalable multi-tenant BGP tool as an important component of a high-performance and high-availability SDN based hybrid cloud network solution."
  - institution: 
      name: "AT\\&T Labs Research"
      address: Bedminster, NJ, USA
    duration: 2016.5 - 2016.7
    role: Research Intern
    mentor: He Yan and Zihui Ge
    achievements:
      - "Developed tools to automate the dynamics analysis in services supported by virtualized environment."

# Projects
project:
  - name: Crossbar Scheduling 
    duration: 2016.2 - Present
    contributions:
      - "Designed a suite of simple distributed/parallel crossbar scheduling algorithms, which can exactly or approximately emulate the linear-time centralized version ({\\it i.e.,} SERENA) in logarithmic rounds with almost the same delay performance."
      - "Designed a simple yet effective ``add-on'' crossbar scheduling algorithm for input-queued switches, which can boost the performance (switch throughput or delay or both) of existing crossbar scheduling algorithms ({\\it e.g.}, iSLIP and SERENA) with almost ``no'' computational overhead. (SIGMETRICS 2017)"
      - "Built an efficient and flexible simulator for crossbar scheduling in input-queued switches." 
  - name: Time Capsule for Online Social Activities
    duration: 2015.9 - Present
    contributions:
      - "Designed a hybrid streaming-sampling algorithm for high accurate measurements of Online Social Networking (OSN) cascade statistics, using limited memory, which decreased the errors (measured in $\\ell_2$) by more than one order of magnitude. (ICCCN 2017)"
  - name: Network Virtualization over Elastic Optical Networks
    duration: 2012.2 - 2015.6
    contributions:
      - "Designed a novel virtual network embedding algorithm, which increased the network utilization and decreased the time complexity. (INFOCOM 2014)"
      - "Proposed the first integer linear programming formulations for the virtual optical network embedding problems in the contexts of flexible-grid elastic optical networks, and designed efficient algorithms which achieved much better performance. (Journal of Lightwave Technology)"
      - "Proved the first inapproximability result of the location-constrained virtual network embedding (LC-VNE) problems, and designed efficient algorithms for solving LC-VNE, which achieved much better performance (in terms of both resource consumption and fairness). (IEEE/ACM Transactions on Networking)"
      - "Built the first OpenFlow-based network virtualization platform where the underlying infrastructure is the flexible-grid elastic optical networks. (Master Thesis)"

# Publication
publication:
  bibfile: "./data/long_gong_pub.bib"
  full:
    url: https://scholar.google.com/citations?user=qtAikfAAAAAJ&hl=en
    name: Google Scholar
  cite_key:
    - GongHuangTuneEtAl2017
    - GongTuneLiuEtAl2017
    - ZhuLiuWangEtAl2016
    - GongJiangWangEtAl2016
    - YangGongZhu2016
    - JiangWangGongEtAl2015
    - YangGongZhouEtAl2015
    - YaoLuGongEtAl2015
    - GongWenZhuEtAl2014
    - GongZhu2014
    - JiangGongZuqing2014
    - GongWenZhuEtAl2013
    - GongZhaoWenEtAl2013
    - GongZhouLiuEtAl2013
    - LiuGongZhu2013
    - LiuGongZhu2013a
    - LiuGongZhu2013b
    - LuZhouGongEtAl2013
    - ZhangShiGongEtAl2013
    - GongZhouLuEtAl2012
    - LuZhouGongEtAl2012
    - ZhouLuGongEtAl2012

# Talks
talk:
  - title: "Queue-Proportional Sampling: A Better Approach to Crossbar Scheduling for Input-Queued Switches"
    where: ACM SIGMETRICS 2017, Urbana-Champaign, Illinois, USA
  - title: Toward Profit-Seeking Virtual Network Embedding Algorithm via Global Resource Capacity
    where: IEEE INFOCOM 2014, Toronto, Canada
  - title: Revenue-Driven Virtual Network Embedding Based on Global Resource Information
    where: IEEE GLOBECOM 2013, Atlanta, GA, USA
  - title: Dynamic Transparent Virtual Network Embedding over Elastic Optical Infrastructures
    where: IEEE ICC 2013, Budapest, Hungary

# Skills
skill:
  - description: Programming Languages
    details:
      - name: C++
        proficiency: proficient
      - name: Python
        proficiency: fluent
      - name: Java
        proficiency: prior experience

# Honors
honor:
  - name: Student Travel Grant Award
    details:
      - where: ACM SIGMETRICS
        when: 2017
  - name: Excellent Graduate
    details:
      - where: University of Science and Technology of China, Hefei, Anhui, China
        when: 2015
  - name: National Scholarship (for Master Students)
    details:
      - where: University of Science and Technology of China, Hefei, Anhui, China
        when: 2013
  - name: Best Paper Award
    details:
      - where: ONS Symposium, IEEE GLOBECOM 2013 
        when: 2013
      - where: ONS Symposium, IEEE ICC 2013
        when: 2013

# Services
service:
  - type: Reviewer
    where:
      - IEEE INFOCOM 2016
      - IEEE Communication Letters
      - IEEE Transactions on Parallel and Distributed Systems
      - IEEE/ACM Transactions on Networking
      - IEEE/OSA Journal of Optical Communications and Networking



